version: '3.1'

services:
  database:
    container_name: colivery_database
    image: postgis/postgis:11-3.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: colivery
      POSTGRES_USER: colivery
      POSTGRES_DB: colivery
